l2:
  gtype: number
  precision: 1
  min_order: -6
  max_order: 3
  positive: yes


loss_learning:
  nprofessors:
    gtype: number
    precision: 1
    min_order: 0
    max_order: 0
    positive: yes
    avoid_zero: yes

  loss_predictor:
    name:
      gtype: set
      domain:
        - CorrLossPredictor
        - MLPLossPredictor

    inter_layer:
      gtype: set
      domain:
        - True
        - False
    width:
      gtype: set
      domain:
        - 1
        - 2
        - 3

  optimizer:
    name:
      gtype: set
      domain:
        - SGD
        - Adam

    lr:
      gtype: number
      precision: 1
      min_order: -5
      max_order: -2
      positive: yes
      avoid_zero: yes

    nesterov:
      gtype: set
      domain:
        - True
        - delete

    momentum:
      gtype: number
      precision: 2
      min_order: -2
      max_order: -2
      positive: yes

  param_samples:
    gtype: number
    precision: 1
    min_order: 0
    max_order: 0
    positive: yes
    avoid_zero: yes

  noise_intensity:
    gtype: number
    precision: 2
    min_order: -2
    max_order: -2
    positive: yes

  noise_type:
    gtype: set
    domain:
      - absolute
      - relative
      - max_layer

  full_grad:
    gtype: set
    domain:
      - yes
      - no

  c0:
    gtype: number
    precision: 1
    min_order: -5
    max_order: 0
    positive: yes

  c1:
    gtype: number
    precision: 1
    min_order: -5
    max_order: 0
    positive: yes

  c2:
    gtype: number
    precision: 1
    min_order: -5
    max_order: 0
    positive: yes

  ccos:
    gtype: number
    precision: 1
    min_order: -5
    max_order: 3
    positive: yes

  coptim:
    gtype: number
    precision: 1
    min_order: -5
    max_order: 0
    positive: yes



constraints:
  loss_learning.optimizer.name:
    Adam:
      - loss_learning.optimizer.momentum: delete
      - loss_learning.optimizer.nesterov: delete


meta:
  steps: 5000
  selection: squared_rank
  drop_below_zero: yes
