nstudents:
  - 9
  - 19

random_students:
  - yes
  - no

reset_student:
  - 6400
  - 12800
  - 25600
  - 51200

loss_learning:
  encoder:
    name:
      - ConvEncoder
      - LinearEncoder

  nz:
    - 32
    - 64

  c_contrast_kl:
    - 0.1
    - 0.5
    - 1.0

  c_d:
    - 0.1
    - 0.5
    - 1.0

  c_latent_kl:
    - 0.1
    - 0.5

