reset_student:
  gtype: number
  precision: 2
  positive: yes
  avoid_zero: no
  min_order: 4
  max_order: 4

nstudents:
  gtype: set
  domain:
    - 1
    - 3
    - 5
    - 7
    - 9

c_l2:
  gtype: number
  precision: 1
  positive: yes
  avoid_zero: no
  min_order: -5
  max_order: -3

loss_learning:

  generator:
    ngf:
      gtype: set
      domain:
        - 8
        - 16

  c_nll:
    gtype: number
    precision: 1
    positive: yes
    avoid_zero: no
    min_order: -3
    max_order: 0

  c_kl:
    gtype: number
    precision: 1
    positive: yes
    avoid_zero: no
    min_order: -3
    max_order: 0

  c_grad_mse:
    gtype: number
    precision: 1
    positive: yes
    avoid_zero: no
    min_order: -3
    max_order: 2
    
  c_grad_cos:
    gtype: number
    precision: 1
    positive: yes
    avoid_zero: no
    min_order: -3
    max_order: 0

  c_next_nll:
    gtype: number
    precision: 1
    positive: yes
    avoid_zero: no
    min_order: -4
    max_order: 0

  c_hess:
    gtype: number
    precision: 1
    positive: yes
    avoid_zero: no
    min_order: -6
    max_order: -2

  c_d:
    gtype: number
    precision: 1
    positive: yes
    avoid_zero: no
    min_order: -3
    max_order: 0

  c_recon:
    gtype: number
    precision: 1
    positive: yes
    avoid_zero: no
    min_order: -3
    max_order: 0

  c_latent_kl:
    gtype: number
    precision: 1
    positive: yes
    avoid_zero: yes
    min_order: -4
    max_order: 0

  optimizer:
    name:
      gtype: set
      domain:
        - Adam
        - SGD
    nesterov:
      gtype: set
      domain:
        - True
        - False
    momentum:
      gtype: number
      precision: 2
      positive: yes
      avoid_zero: yes
      min_order: -2
      max_order: -2

constraints:
  loss_learning.optimizer.name:
    Adam:
      - loss_learning.optimizer.momentum: delete
      - loss_learning.optimizer.nesterov: delete


meta:
  steps: 5000
  selection: squared_rank
