dataset: 'fashion_mnist'
proj: 'conv'
ds_size: 100
data_batch: 100
in_size: [1000]
out_size: 10
n_proj: 10
epochs: 10000
lin:
  layers: [256]
conv:
  layers: [[5,5,8],[3,3,16],[256]]
activation: 'relu'
verbose: 1
reset_freq: 100
objective: 'kl'
align_grad: 0
batch_size: 10
optim: 'adam'
lr: 0.01
train_proj: 100
test_steps: 1000
real_divergence: 0
