no_cuda: no
run_id: 0
verbose: 1

dataset: FashionMNIST
batch_size: 128
test_batch_size: 10000
in_size: [1, 32, 32]

random_params: yes

c_l2: 0
nepochs: 2

evaluation:
  freq: 24000
  nstudents: 3
  teaching_steps: 200
  eval_freq: 25
  async: yes
  continuous: yes

student:
  name: ConvNet
  channels: [32, 32]
  units: [100]
  use_bias: no
  use_dropout: yes
  use_batch_norm: no

student_optimizer:
  name: Adam
  lr: 0.001

professor:
  name: GenerativeProfessor
  nstudents: 12
  random_students: no
  trained_on_fake: 8

  students_per_batch: 2


  nz: 32
  nperf: 16

  generator:
    name: SkipGenerator
    ngf: 16

  encoder:
    name: LinearEncoder
    nef: 8

  discriminator:
    name: OutputDiscriminator

  label_to_discriminator: yes
  permute_before_discriminator: yes

  siamese:
    name: ConvNet
    channels: [32, 32]
    units: [64]
    use_bias: yes
    use_dropout: yes
    use_batch_norm: no

  siamese_detach_other: yes
  contrast_from_real_data: yes
  siamese_margin: 1.0

  optimizer:
    name: Adam
    lr: .001

  c_nll: 0
  c_kl: 1
  c_contrast_kl: 0
  c_adv: 0
  c_siamese: 1
  c_grad_mse: 0
  c_grad_cos: 0
  c_next_nll: 0
  c_contrast_next_nll: 0
  c_next_nll2: 0
  c_next_kl: 0
  c_hess: 0
  c_d: 0
  c_recon: 0
  c_latent_kl: 1
  next_lr: .001
  target_dropout: 0

  grad_type: example
  grad_samples: 128

  eval_samples: 128

  student_reset: powspace

  report_freq: 16384