dataset: 'mnist'
memory_size: 100
proj: 'conv'
ds_size: 100
data_batch: 100
in_size: [1000]
out_size: 10
n_proj: 50
epochs: 300
lin:
  layers: [256]
conv:
  layers: [[5,5,32],[3,3,64],[128]]
  dropout: 0
activation: 'relu'
verbose: 0
reset_freq: 1
objective: 'grad_cos'
align_grad: 0
batch_size: 16
optim: 'sgd'
lr: 0.005
train_proj: 0
test_epochs: 20
train_epochs: 100
min_test_it: 3000
real_divergence: 0.1
full_memory: 1
use_gpu: 1
parallel: 0